name: 04 - Rollback Updater (Staging)

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Tag Antiga para Reverter (ex: v1.0.0)'
        required: true
      confirm:
        description: 'Digite EXECUTAR para confirmar'
        required: true

jobs:
  time-travel:
    if: github.event.inputs.confirm == 'EXECUTAR'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ⏱️ Voltar no Tempo
        run: |
          $TAG = "${{ github.event.inputs.version_tag }}"
          git checkout $TAG
        shell: pwsh

      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: '8.0.x' }

      - name: 🔨 Recompilar como Staging
        run: |
          $ver = "${{ github.event.inputs.version_tag }}".TrimStart('v')
          dotnet publish "LauncherUpdater/LauncherUpdater.csproj" --configuration Release --self-contained true -r win-x64 --output ./publish /p:Version=$ver /p:DefineConstants="STAGING" /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
        shell: pwsh

      - name: 📦 Estruturar Pacote Rollback
        shell: pwsh
        run: |
          $targetTag = "${{ github.event.inputs.version_tag }}-rc"
          $ver = "${{ github.event.inputs.version_tag }}".TrimStart('v')
          
          New-Item -ItemType Directory -Force -Path "./deploy_payload/$targetTag"

          $zipName = "launcherupdater_release.zip"
          Compress-Archive -Path ./publish/* -DestinationPath "./deploy_payload/$targetTag/$zipName"
          $hash = (Get-FileHash -Path "./deploy_payload/$targetTag/$zipName").Hash

          $urlZipProtegida = "https://aux.newsystem.net.br/endpoint_pdv/download_gate.php?file=LauncherUpdaterVersions/$targetTag/$zipName&env=staging"
          
          @{ Version = "$ver.0"; Url = $urlZipProtegida; Checksum = $hash } | ConvertTo-Json | Set-Content "./deploy_payload/$targetTag/LauncherUpdaterVersion.json"
          
          @{ CurrentFolder = $targetTag } | ConvertTo-Json | Set-Content "./deploy_payload/LauncherUpdaterVersionMaster.json"

      - name: 🔑 Configurar Chave SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: 🚀 Upload do Rollback via SCP
        run: scp -v -r -o StrictHostKeyChecking=no -P 1891 ./deploy_payload/* "${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }}:public_html/auxiliares/endpoint_pdv/updates_staging/LauncherUpdaterVersions/"
        shell: bash